language: node_js
node_js:
    - 10
branchs:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - yarn install
script:
    - yarn test && yarn build
after_script:
    - cd build
    - git init
    - git config user.name "qqqqqcy"
    - git config user.email "qqqqqcy@gmail.com"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
env:
    global:
        - GH_REF: github.com/jdthfe/edm.git
        - secure: oGpBn+qB9J4alvSQAY9kxHkoxTH/F3MznA8R9K+U40U3iy2xZ7KfRoDCGlRyt5iFqVUZ2YGWDY+uv9owoikfg6nkGtnKRwB9JINSLDapJJscNAA5cw9athG07Y8xI2Ryi57e7ENWQWJiGtEctvI6orz2RvZnmPvssMwmTFaHBoK/y54feBChBTv/WZvSpvyjPVqXE6GJw++5tKFR3Ux+Fcg9f8n4Rn2yHf8W87Rl096DVXG205PTarhnhXzjSSTE9y+NQY9DWoMd5QsSG7bDPrgXjbmgfx8TYoUReSabwl7QoUoSawRhWfkfgfNnirLMQJLzOF0TFOze/Oqh4NonEq5VBLRc5wluL/SXGeKLnB/rLJ0D21/8wRO5jwiTNIwAiBPinUelasWRNBopVoq/1kAjZbS1z8M71e4wTkU8v1AyRMVs770lbws27N3R0MiyrmndRNMUvyA5pf+qX5D2rH8CBTjDwzG2GOUc8Ew3eqNat8VtILqUtrWN6yWlh5wq2WlHlmODISMJo7SNGkGlRlVeKM6XYqeTOv59omKVf8kHVYNDb8MjuLv7wqlDQjanDIYHoVG9yOoRKOfT/QXzpcUHwOzbmhLxJ8p6Dxac2cU1crw4B4/xI8Oj5MyFmSglQXgSEHrxbKNIm1EZYAlLpH58xuPYHlEN7CK0+7MBBa4=
