language: node_js
node_js:
    - 10
branchs:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - yarn install
script:
    - yarn test && yarn build
after_script:
    - cd build
    - git init
    - git config user.name "qqqqqcy"
    - git config user.email "qqqqqcy@gmail.com"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
env:
    global:
        - GH_REF: github.com/jdthfe/edm.git
        - secure: Bg7H7ma0w+8MWLHMbInsMq1+LNA02znTJjWhmvwVxmxyAV93WlCRm+PDMhF98xoxn9XjKVua9Nca51XHQzyu/kAt8nJlRS6vfVZXKUbv2jbILb2AAjJ3RxVlXFVnDGj/j0ULM/36v/gJOfPd6UWZNCBGk+XHj5rfbsTUqzlWfGQiMhYNvHhTX8DytZFJCaH5xek6QTXXiz9CvSkLMQk2HdGw9nPd8yFeQpq3r3SbBrU/HmyhoyJ1nkFl1Fh3ycJiL712o92uEKdrqPvGPSzm9B+kPxxYar4sm0NaL59cNiDsrLnpLmluLn03qvhoaNUOIOvZTfFL33pLNvO/v2WD9hKTJi3i3CXpfn8OHxglMM72WdlNj7xNGG0K8wmNlIAJoEX4hbbzCZjDKEpdVLca65Adtw8iaYx0HeO/H54mGfyprZhzANV4rfeDJhAxMQfmZWr3x+8sVQKr6Y2LabUAofNcB2kBi8gujCz7Ibii/yP/WgtXuU8jvmXz9OnXcxximNK+ewOvbukwYf5WZJ8JBX2aIRgV/4dt2wKzxsm1pi5a4Ex3RwUoHj+28/AY+wZUsMNrUqGodDMumEld1Kd23jkQKwz7BtFSlzq7UauZlLQVbpAu8z+t1lZV82BCPgxWMIVoQa3Gs9tP+IayLegDTFNFY4bT/T2apBANFeryDMg=
